name: telegram message
on:
  pull_request:
    types: [opened, reopened]
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: fetch PR info
        id: fetch-pr
        uses: actions/github-script@v6
        with:
          script: | 
            const result = await github.request(context.payload.pull_request.url)
            console.log(result.data)
            return result.data
      - name: Get result
        run: echo "${{steps.fetch-pr.outputs}}"
#       - name: send telegram message on PR
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_CHAT_ID }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: |
#             ${{ github.actor }} created Pull Request
#             Title: ${{ steps.fetch-pr.outputs.result.title }}
#             See changes: ${{ github.event.pull_request.html_url }}
            
#             Reviewers: ${{ github.event.pull_request.requested_reviewers[0].login }}, ${{ github.event.pull_request.requested_reviewers[1].login }}
