name: telegram message
on:
  pull_request:
    types: [opened, reopened]
    branches:
    - main
jobs:
  fetch:
    name: fetch
    uses: ./.github/workflows/fetch_pr_info.yml
    with:
      pr_url: ${{ github.pull_request.url }}

  notify:
    name: Notify
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on PR
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} открыл PR: ${{ fromJSON(needs.fetch.outputs.result).title }}
            ${{ fromJSON(needs.fetch.outputs.result).html_url }}
            
            Reviewers: ${{ fromJSON(needs.fetch.outputs.result).requested_reviewers[0].login }}, ${{ fromJSON(needs.fetch.outputs.result).requested_reviewers[1].login }}
